[build]
command = "npx vite build"
publish = "dist"

[[redirects]]
  from = "/cars-data.xml"
  to = "/.netlify/functions/cars-data"
  status = 200

[[redirects]]
  from = "/share"
  to = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/public/img.php"
  to = "/.netlify/functions/img-proxy-wiselease"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200