[build]
command = "npx vite build"
publish = "dist"

[[redirects]]
from = "/cars-data.xml"
to = "/.netlify/functions/cars-data"
status = 200

[[redirects]]
from = "/share"
to = "/.netlify/functions/share"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200